/**
 * C# licensing module for VEYLIX Revit add-ins. The admin panel fills in the placeholders per product
 * (server URL, product slug, RSA public key) and serves it as VeylixLicense.cs.
 *
 * Written for C# 7.3 so it compiles unchanged for .NET Framework 4.8 (Revit 2021–2024) and .NET 8 (Revit 2025+).
 * No NuGet packages: HTTP via HttpWebRequest, storage encryption via Windows DPAPI (P/Invoke).
 */
export const CSHARP_TEMPLATE = String.raw`// =====================================================================================
//  VeylixLicense.cs  -  licensing for "{{PRODUCT_NAME}}"  (product id: {{PRODUCT_SLUG}})
//  Generated by the VEYLIX admin panel on {{GENERATED_AT}}. Do not share this file publicly.
//
//  SETUP (once):
//   1. Add this file to your Revit add-in project.
//   2. WinForms is used for the key dialog:
//        .NET Framework 4.8 (Revit 2021-2024): reference System.Windows.Forms and System.Drawing
//        .NET 8 (Revit 2025+): add <UseWindowsForms>true</UseWindowsForms> to your .csproj
//   3. First line of EVERY IExternalCommand.Execute:
//        if (!Veylix.Licensing.VeylixLicense.Require()) return Result.Cancelled;
//   4. Optional ribbon button that shows time remaining / lets the user change key:
//        Veylix.Licensing.VeylixLicense.ShowStatus();
//   5. Rebuild, obfuscate the DLL (recommended), then upload the build folder in the admin panel.
//
//  HOW IT WORKS
//   - The user enters a product key. The server binds it to this PC and returns a license
//     signed with the VEYLIX RSA private key. This file only contains the PUBLIC key, so a
//     license cannot be forged or edited.
//   - The license is valid for the check interval set in the admin panel (default 30 days).
//     When it runs out, the plugin asks for the key again and shows the time remaining.
//   - The license file is encrypted with Windows DPAPI and tied to this PC's hardware ID: hashed SMBIOS UUID,
//     board serial, CPU id, Windows MachineGuid, drive serial and physical MAC addresses (never raw values).
//     Small changes (Windows reinstall, new network card, renamed PC) keep the license; another PC does not.
//   - One working license per plugin per PC: a second key for the same plugin is refused on that PC.
//   - Moving the Windows clock back is detected. Revoked keys and device resets take effect
//     at the next online check (at most every 6 hours while Revit is running).
// =====================================================================================

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Win32;

namespace Veylix.Licensing
{
    public static class VeylixLicense
    {
        public const string ServerUrl = "{{SERVER_URL}}";
        public const string SupportEmail = "{{SUPPORT_EMAIL}}";
        public const string ProductSlug = "{{PRODUCT_SLUG}}";
        public const string ProductName = "{{PRODUCT_NAME}}";
        private const string PublicKeyXml = "{{PUBLIC_KEY_XML}}";

        private static readonly object Sync = new object();
        private static LicenseState _state;
        private static bool _loaded;
        private static int _refreshing;
        private static bool _warnedThisSession;

        /// <summary>True when a valid, unexpired license exists on this PC.</summary>
        public static bool IsLicensed
        {
            get { LicenseState s = Load(); return s != null && s.IsCurrentlyValid(); }
        }

        /// <summary>Time until the plugin asks for the product key again.</summary>
        public static TimeSpan RemainingTime
        {
            get
            {
                LicenseState s = Load();
                if (s == null) return TimeSpan.Zero;
                TimeSpan left = s.ValidUntilUtc - DateTime.UtcNow;
                return left < TimeSpan.Zero ? TimeSpan.Zero : left;
            }
        }

        /// <summary>
        /// Call at the start of every command. Returns true when the user may continue.
        /// Shows the product key dialog when there is no valid license.
        /// </summary>
        public static bool Require()
        {
            try
            {
                LicenseState s = Load();
                if (s != null && s.IsCurrentlyValid())
                {
                    s.LastSeenUtc = DateTime.UtcNow;
                    Save(s);
                    RefreshInBackground(s);
                    if (!_warnedThisSession)
                    {
                        string warning = Warning(s);
                        if (warning != null)
                        {
                            _warnedThisSession = true;
                            MessageBox.Show(Owner(), warning, "VEYLIX license", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
                    }
                    return true;
                }

                string reason;
                if (s == null) reason = "Enter your product key to activate " + ProductName + " on this PC.";
                else if (s.ClockTampered) reason = "Your system clock was changed. Enter your product key to continue.";
                else if (s.IsTrial && s.Ended) reason = "Your free trial has ended. Enter a product key to keep using " + ProductName + ".";
                else if (s.Ended) reason = "Your license has ended. Renew it on the VEYLIX website (same key), then enter your key here.";
                else reason = "It's time to confirm your license. Enter your product key to continue.";

                using (LicenseDialog dialog = new LicenseDialog(reason, s != null ? s.Key : ""))
                {
                    dialog.ShowDialog(Owner());
                    return dialog.KeyAccepted;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(Owner(), "License check failed: " + ex.Message, "VEYLIX license", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
        }

        /// <summary>Shows the license status (time remaining) and lets the user enter another key.</summary>
        public static void ShowStatus()
        {
            LicenseState s = Load();
            string text = s != null && s.IsCurrentlyValid()
                ? "Licensed. Key " + s.Key + "\nNext key check in " + FormatSpan(s.ValidUntilUtc - DateTime.UtcNow) +
                  (s.RenewDueUtc.HasValue ? (s.IsTrial ? "\nTrial ends " : "\nRenew by ") + FormatDate(s.RenewDueUtc.Value) : "") +
                  (s.InGrace ? "\nGrace period: works until " + FormatDate(s.ExpiresAtUtc.Value) : "") +
                  (s.IsTrial ? "\n(Free trial)" : "")
                : "Not activated on this PC.";
            using (LicenseDialog dialog = new LicenseDialog(text, s != null ? s.Key : ""))
            {
                dialog.ShowDialog(Owner());
            }
        }

        // ------------------------------------------------------------------ activation

        internal static bool Activate(string key, out string message)
        {
            string nonce = RandomToken(24);
            Dictionary<string, string> fields = new Dictionary<string, string>
            {
                { "key", key.Trim() },
                { "deviceId", DeviceId() },
                { "deviceName", Environment.MachineName },
                { "components", Hardware.Components() },
                { "product", ProductSlug },
                { "nonce", nonce },
            };
            string[] lines;
            try
            {
                lines = Post("/api/license/activate", fields, 15000);
            }
            catch (Exception ex)
            {
                message = "Could not reach the license server. Check your internet connection.\n(" + ex.Message + ")";
                return false;
            }

            if (lines.Length >= 3 && lines[0] == "OK")
            {
                LicenseState s = LicenseState.FromSigned(lines[1], lines[2]);
                if (s == null || s.Nonce != nonce || s.DeviceId != DeviceId() || !s.MatchesProduct())
                {
                    message = "The server response could not be verified.";
                    return false;
                }
                s.LastSeenUtc = DateTime.UtcNow;
                s.LastOnlineUtc = DateTime.UtcNow;
                Save(s);
                message = "Activated. The next key check is in " + FormatSpan(s.ValidUntilUtc - DateTime.UtcNow) + ".";
                return true;
            }
            message = lines.Length >= 3 ? lines[2] : "Activation failed.";
            return false;
        }

        private static void RefreshInBackground(LicenseState s)
        {
            if ((DateTime.UtcNow - s.LastOnlineUtc).TotalHours < 6) return;
            if (Interlocked.Exchange(ref _refreshing, 1) == 1) return;
            string key = s.Key;
            Task.Run(() =>
            {
                try
                {
                    string nonce = RandomToken(24);
                    string[] lines = Post("/api/license/status", new Dictionary<string, string>
                    {
                        { "key", key },
                        { "deviceId", DeviceId() },
                        { "components", Hardware.Components() },
                        { "product", ProductSlug },
                        { "nonce", nonce },
                    }, 8000);

                    if (lines.Length >= 3 && lines[0] == "OK")
                    {
                        LicenseState fresh = LicenseState.FromSigned(lines[1], lines[2]);
                        if (fresh != null && fresh.Nonce == nonce && fresh.DeviceId == DeviceId() && fresh.MatchesProduct())
                        {
                            fresh.LastSeenUtc = DateTime.UtcNow;
                            fresh.LastOnlineUtc = DateTime.UtcNow;
                            Save(fresh); // adopts admin changes (shorter interval, forced re-check)
                        }
                    }
                    else if (lines.Length >= 2 && lines[0] == "ERROR")
                    {
                        string code = lines[1];
                        if (code == "revoked" || code == "device_mismatch" || code == "expired" || code == "invalid_key" || code == "not_activated" || code == "wrong_product" || code == "hw_limit")
                            Clear(); // key revoked or moved to another PC: ask again next time
                    }
                }
                catch
                {
                    // offline: keep working until the signed license runs out
                }
                finally
                {
                    Interlocked.Exchange(ref _refreshing, 0);
                }
            });
        }

        // ------------------------------------------------------------------ storage

        private static string StatePath()
        {
            string dir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "VEYLIX");
            Directory.CreateDirectory(dir);
            return Path.Combine(dir, ProductSlug + ".lic");
        }

        private static LicenseState Load()
        {
            lock (Sync)
            {
                if (_loaded) return _state;
                _loaded = true;
                try
                {
                    string path = StatePath();
                    if (!File.Exists(path)) return _state = null;
                    string text = Encoding.UTF8.GetString(Dpapi.Unprotect(File.ReadAllBytes(path), Entropy()));
                    string[] parts = text.Split('\n');
                    if (parts.Length < 4) return _state = null;
                    LicenseState s = LicenseState.FromSigned(parts[0], parts[1]);
                    // Same PC: identical hardware ID, or enough hardware signals in common after a small change.
                    if (s == null || !s.MatchesProduct() || (s.DeviceId != DeviceId() && !Hardware.Same(s.Components, Hardware.Components()))) return _state = null;
                    s.LastSeenUtc = FromUnix(long.Parse(parts[2], CultureInfo.InvariantCulture));
                    s.LastOnlineUtc = FromUnix(long.Parse(parts[3], CultureInfo.InvariantCulture));
                    return _state = s;
                }
                catch
                {
                    return _state = null;
                }
            }
        }

        private static void Save(LicenseState s)
        {
            lock (Sync)
            {
                string text = s.Payload + "\n" + s.Signature + "\n" + ToUnix(s.LastSeenUtc).ToString(CultureInfo.InvariantCulture) + "\n" + ToUnix(s.LastOnlineUtc).ToString(CultureInfo.InvariantCulture);
                File.WriteAllBytes(StatePath(), Dpapi.Protect(Encoding.UTF8.GetBytes(text), Entropy()));
                _state = s;
                _loaded = true;
            }
        }

        private static void Clear()
        {
            lock (Sync)
            {
                try { File.Delete(StatePath()); } catch { }
                _state = null;
                _loaded = true;
            }
        }

        private static byte[] Entropy()
        {
            return Encoding.UTF8.GetBytes("VEYLIX|" + ProductSlug);
        }

        // ------------------------------------------------------------------ crypto & device

        internal static bool VerifySignature(string payload, string signatureBase64)
        {
            try
            {
                using (RSA rsa = new RSACng())
                {
                    rsa.FromXmlString(PublicKeyXml);
                    return rsa.VerifyData(Encoding.UTF8.GetBytes(payload), Convert.FromBase64String(signatureBase64), HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
                }
            }
            catch
            {
                return false;
            }
        }

        /// <summary>Stable per-PC ID ("W2-" + 40 hex), derived from the hashed hardware signals.</summary>
        public static string DeviceId()
        {
            return Hardware.DeviceId();
        }

        private static string RandomToken(int length)
        {
            const string alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
            byte[] bytes = new byte[length];
            using (RandomNumberGenerator rng = RandomNumberGenerator.Create()) rng.GetBytes(bytes);
            StringBuilder sb = new StringBuilder(length);
            foreach (byte b in bytes) sb.Append(alphabet[b % alphabet.Length]);
            return sb.ToString();
        }

        // ------------------------------------------------------------------ HTTP

        private static string[] Post(string path, IDictionary<string, string> fields, int timeoutMs)
        {
#pragma warning disable SYSLIB0014 // WebRequest/ServicePointManager: kept for .NET Framework 4.8 compatibility
            ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
            string body = string.Join("&", fields.Select(f => Uri.EscapeDataString(f.Key) + "=" + Uri.EscapeDataString(f.Value)).ToArray());
            HttpWebRequest req = (HttpWebRequest)WebRequest.Create(ServerUrl.TrimEnd('/') + path + "?format=text");
#pragma warning restore SYSLIB0014
            req.Method = "POST";
            req.ContentType = "application/x-www-form-urlencoded";
            req.UserAgent = "VeylixLicense/1 (" + ProductSlug + ")";
            req.Timeout = timeoutMs;
            req.ReadWriteTimeout = timeoutMs;
            byte[] bytes = Encoding.UTF8.GetBytes(body);
            req.ContentLength = bytes.Length;
            using (Stream s = req.GetRequestStream()) s.Write(bytes, 0, bytes.Length);
            try
            {
                using (HttpWebResponse resp = (HttpWebResponse)req.GetResponse()) return ReadLines(resp);
            }
            catch (WebException ex)
            {
                HttpWebResponse resp = ex.Response as HttpWebResponse;
                if (resp == null) throw;
                using (resp) return ReadLines(resp);
            }
        }

        private static string[] ReadLines(HttpWebResponse resp)
        {
            using (StreamReader reader = new StreamReader(resp.GetResponseStream(), Encoding.UTF8))
            {
                return reader.ReadToEnd().Replace("\r", "").Split('\n');
            }
        }

        // ------------------------------------------------------------------ helpers

        internal static DateTime FromUnix(long seconds)
        {
            return new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddSeconds(seconds);
        }

        internal static long ToUnix(DateTime utc)
        {
            return (long)(utc - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalSeconds;
        }

        internal static string FormatSpan(TimeSpan t)
        {
            if (t <= TimeSpan.Zero) return "0 minutes";
            if (t.TotalDays >= 1) return (int)t.TotalDays + " day" + ((int)t.TotalDays == 1 ? "" : "s") + ", " + t.Hours + " hour" + (t.Hours == 1 ? "" : "s");
            if (t.TotalHours >= 1) return (int)t.TotalHours + " hour" + ((int)t.TotalHours == 1 ? "" : "s");
            return Math.Max(1, (int)t.TotalMinutes) + " minutes";
        }

        internal static string FormatDate(DateTime utc)
        {
            return utc.ToLocalTime().ToString("d MMM yyyy", CultureInfo.InvariantCulture);
        }

        private static string Warning(LicenseState s)
        {
            DateTime now = DateTime.UtcNow;
            if (s.InGrace)
                return ProductName + ": your license ended on " + FormatDate(s.RenewDueUtc.Value) + ".\n" +
                       "It keeps working until " + FormatDate(s.ExpiresAtUtc.Value) + ". Renew it on the VEYLIX website (your key stays the same).";
            if (s.RenewDueUtc.HasValue && (s.RenewDueUtc.Value - now).TotalDays < 3)
                return s.IsTrial
                    ? ProductName + ": your free trial ends in " + FormatSpan(s.RenewDueUtc.Value - now) + ". Buy a license on the VEYLIX website to keep using it."
                    : ProductName + ": your license ends in " + FormatSpan(s.RenewDueUtc.Value - now) + ".\nRenew it on the VEYLIX website (your key stays the same).";
            TimeSpan left = s.ValidUntilUtc - now;
            if (left.TotalDays < 3)
                return ProductName + ": your license check is due in " + FormatSpan(left) + ".\nYou will be asked for your product key again then.";
            return null;
        }

        internal static IWin32Window Owner()
        {
            return new WindowHandle(Process.GetCurrentProcess().MainWindowHandle);
        }

        private sealed class WindowHandle : IWin32Window
        {
            public WindowHandle(IntPtr handle) { Handle = handle; }
            public IntPtr Handle { get; private set; }
        }
    }

    internal sealed class LicenseState
    {
        public string Payload;
        public string Signature;
        public string Key;
        public string DeviceId;
        public string Scope;
        public DateTime ValidUntilUtc;
        public DateTime IssuedAtUtc;
        public DateTime? ExpiresAtUtc;   // hard stop (end date + grace)
        public DateTime? RenewDueUtc;    // the subscription / trial end date shown to the user
        public string Components = "";
        public int CheckDays;
        public bool IsTrial;
        public string Nonce;
        public DateTime LastSeenUtc;
        public DateTime LastOnlineUtc;

        /// <summary>True when the Windows clock is earlier than a time this license has already seen.</summary>
        public bool ClockTampered
        {
            get
            {
                DateTime now = DateTime.UtcNow;
                return now < LastSeenUtc.AddMinutes(-10) || now < IssuedAtUtc.AddHours(-24);
            }
        }

        public bool IsCurrentlyValid()
        {
            return !ClockTampered && DateTime.UtcNow < ValidUntilUtc && (!ExpiresAtUtc.HasValue || DateTime.UtcNow < ExpiresAtUtc.Value);
        }

        public bool Ended
        {
            get { return ExpiresAtUtc.HasValue && DateTime.UtcNow >= ExpiresAtUtc.Value; }
        }

        public bool InGrace
        {
            get { return !IsTrial && RenewDueUtc.HasValue && ExpiresAtUtc.HasValue && DateTime.UtcNow > RenewDueUtc.Value && DateTime.UtcNow < ExpiresAtUtc.Value; }
        }

        public bool MatchesProduct()
        {
            return Scope == "*" || Scope == VeylixLicense.ProductSlug;
        }

        /// <summary>Parses VLX1|key|device|scope|validUntil|issuedAt|hardStop|days|trial|nonce|components|renewDue after checking the RSA signature.</summary>
        public static LicenseState FromSigned(string payload, string signature)
        {
            if (string.IsNullOrEmpty(payload) || string.IsNullOrEmpty(signature)) return null;
            if (!VeylixLicense.VerifySignature(payload, signature)) return null;
            string[] p = payload.Split('|');
            if (p.Length < 10 || p[0] != "VLX1") return null;
            long expires = long.Parse(p[6], CultureInfo.InvariantCulture);
            return new LicenseState
            {
                Payload = payload,
                Signature = signature,
                Key = p[1],
                DeviceId = p[2],
                Scope = p[3],
                ValidUntilUtc = VeylixLicense.FromUnix(long.Parse(p[4], CultureInfo.InvariantCulture)),
                IssuedAtUtc = VeylixLicense.FromUnix(long.Parse(p[5], CultureInfo.InvariantCulture)),
                ExpiresAtUtc = expires > 0 ? (DateTime?)VeylixLicense.FromUnix(expires) : null,
                CheckDays = int.Parse(p[7], CultureInfo.InvariantCulture),
                IsTrial = p[8] == "1",
                Nonce = p[9],
                Components = p.Length > 10 ? p[10] : "",
                RenewDueUtc = p.Length > 11 && p[11] != "0" && p[11].Length > 0 ? (DateTime?)VeylixLicense.FromUnix(long.Parse(p[11], CultureInfo.InvariantCulture)) : null,
                LastSeenUtc = DateTime.UtcNow,
                LastOnlineUtc = DateTime.UtcNow,
            };
        }
    }

    internal sealed class LicenseDialog : Form
    {
        private readonly TextBox _key;
        private readonly Label _message;
        private readonly Button _activate;
        public bool KeyAccepted { get; private set; }

        public LicenseDialog(string message, string currentKey)
        {
            Text = VeylixLicense.ProductName + " - License";
            FormBorderStyle = FormBorderStyle.FixedDialog;
            StartPosition = FormStartPosition.CenterParent;
            MaximizeBox = false;
            MinimizeBox = false;
            ShowInTaskbar = false;
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(460, 250);
            Font = new Font("Segoe UI", 9.5f);
            BackColor = Color.FromArgb(18, 20, 26);
            ForeColor = Color.FromArgb(245, 247, 250);

            Label title = new Label { Text = "VEYLIX  " + VeylixLicense.ProductName, Font = new Font("Segoe UI Semibold", 12f), AutoSize = true, Location = new Point(20, 18), ForeColor = Color.FromArgb(0, 229, 255) };
            _message = new Label { Text = message, Location = new Point(20, 52), Size = new Size(420, 58), ForeColor = Color.FromArgb(201, 206, 216) };
            Label keyLabel = new Label { Text = "Product key", AutoSize = true, Location = new Point(20, 116), ForeColor = Color.FromArgb(139, 146, 161) };
            _key = new TextBox { Text = currentKey ?? "", Location = new Point(20, 136), Size = new Size(420, 28), Font = new Font("Consolas", 11f), CharacterCasing = CharacterCasing.Upper };
            _activate = new Button { Text = "Activate", Location = new Point(330, 196), Size = new Size(110, 32), BackColor = Color.FromArgb(0, 229, 255), ForeColor = Color.FromArgb(0, 22, 26), FlatStyle = FlatStyle.Flat };
            _activate.FlatAppearance.BorderSize = 0;
            Button buy = new Button { Text = "Buy / free trial", Location = new Point(190, 196), Size = new Size(130, 32), FlatStyle = FlatStyle.Flat, ForeColor = Color.FromArgb(245, 247, 250) };
            Button close = new Button { Text = "Close", Location = new Point(20, 196), Size = new Size(90, 32), FlatStyle = FlatStyle.Flat, ForeColor = Color.FromArgb(139, 146, 161), DialogResult = DialogResult.Cancel };

            LinkLabel help = new LinkLabel { Text = "Need help? " + VeylixLicense.SupportEmail, AutoSize = true, Location = new Point(20, 170), LinkColor = Color.FromArgb(0, 229, 255), ActiveLinkColor = Color.FromArgb(94, 240, 255), ForeColor = Color.FromArgb(139, 146, 161) };
            help.LinkArea = new LinkArea("Need help? ".Length, VeylixLicense.SupportEmail.Length);
            help.LinkClicked += delegate
            {
                try { Process.Start(new ProcessStartInfo("mailto:" + VeylixLicense.SupportEmail + "?subject=" + Uri.EscapeDataString(VeylixLicense.ProductName + " license")) { UseShellExecute = true }); } catch { }
            };

            _activate.Click += OnActivate;
            buy.Click += delegate
            {
                // The device ID lets the website refuse to sell this plugin twice to the same PC.
                try { Process.Start(new ProcessStartInfo(VeylixLicense.ServerUrl.TrimEnd('/') + "/en/products/" + VeylixLicense.ProductSlug + "?device=" + VeylixLicense.DeviceId()) { UseShellExecute = true }); } catch { }
            };

            Controls.AddRange(new Control[] { title, _message, keyLabel, _key, help, _activate, buy, close });
            AcceptButton = _activate;
            CancelButton = close;
        }

        private void OnActivate(object sender, EventArgs e)
        {
            string key = _key.Text.Trim();
            if (key.Length < 10)
            {
                _message.Text = "Enter the product key you received (VLX-XXXX-XXXX-XXXX-XXXX).";
                return;
            }
            _activate.Enabled = false;
            Cursor = Cursors.WaitCursor;
            string result;
            bool ok = VeylixLicense.Activate(key, out result);
            Cursor = Cursors.Default;
            _activate.Enabled = true;
            _message.Text = result;
            _message.ForeColor = ok ? Color.FromArgb(34, 211, 170) : Color.FromArgb(255, 92, 122);
            if (ok)
            {
                KeyAccepted = true;
                DialogResult = DialogResult.OK;
                MessageBox.Show(this, result, "VEYLIX license", MessageBoxButtons.OK, MessageBoxIcon.Information);
                Close();
            }
        }
    }

    /// <summary>
    /// Hardware identity. Collects hashed signals (never raw values) and decides whether two signal lists are the
    /// same PC. The rule MUST stay identical to src/lib/server/hardware.ts on the website.
    /// </summary>
    internal static class Hardware
    {
        private static readonly string[] Types = { "uuid", "board", "cpu", "mg", "vol", "mac" };
        private static string _components;
        private static string _deviceId;

        private static int Weight(string type)
        {
            switch (type)
            {
                case "uuid": return 3;
                case "mac": case "board": case "mg": return 2;
                default: return 1;
            }
        }

        public static string DeviceId()
        {
            if (_deviceId != null) return _deviceId;
            string c = Components();
            string basis = c.Length > 0 ? c : "VLXHW-EMPTY|" + Environment.MachineName.ToUpperInvariant();
            _deviceId = "W2-" + Sha256Hex(basis).Substring(0, 40);
            return _deviceId;
        }

        /// <summary>"type:hash,..." sorted like the server's formatComponents().</summary>
        public static string Components()
        {
            if (_components != null) return _components;
            List<KeyValuePair<string, string>> list = new List<KeyValuePair<string, string>>();
            try
            {
                string uuid, board, cpu;
                ReadSmbios(out uuid, out board, out cpu);
                if (uuid != null) list.Add(Pair("uuid", uuid));
                if (board != null) list.Add(Pair("board", board));
                if (cpu != null) list.Add(Pair("cpu", cpu));
            }
            catch { }
            try
            {
                using (RegistryKey hklm = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64))
                using (RegistryKey k = hklm.OpenSubKey(@"SOFTWARE\Microsoft\Cryptography"))
                {
                    string mg = k != null ? (k.GetValue("MachineGuid") as string) : null;
                    if (!string.IsNullOrWhiteSpace(mg)) list.Add(Pair("mg", mg.Trim().ToLowerInvariant()));
                }
            }
            catch { }
            try
            {
                uint serial, maxLen, flags;
                if (Native.GetVolumeInformation(Path.GetPathRoot(Environment.SystemDirectory), null, 0, out serial, out maxLen, out flags, null, 0) && serial != 0)
                    list.Add(Pair("vol", serial.ToString("X8", CultureInfo.InvariantCulture)));
            }
            catch { }
            try
            {
                foreach (string mac in PhysicalMacs()) list.Add(Pair("mac", mac));
            }
            catch { }

            List<string> parts = new List<string>();
            foreach (string type in Types)
            {
                List<string> hashes = list.Where(p => p.Key == type).Select(p => p.Value).Distinct().OrderBy(h => h, StringComparer.Ordinal).ToList();
                if (type != "mac" && hashes.Count > 1) hashes = hashes.Take(1).ToList();
                foreach (string h in hashes.Take(8)) parts.Add(type + ":" + h);
            }
            _components = string.Join(",", parts.ToArray());
            return _components;
        }

        private static KeyValuePair<string, string> Pair(string type, string value)
        {
            return new KeyValuePair<string, string>(type, Sha256Hex("VLXHW|" + type + "|" + value).Substring(0, 16));
        }

        internal static string Sha256Hex(string text)
        {
            using (SHA256 sha = SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(Encoding.UTF8.GetBytes(text));
                StringBuilder sb = new StringBuilder(hash.Length * 2);
                foreach (byte b in hash) sb.Append(b.ToString("x2", CultureInfo.InvariantCulture));
                return sb.ToString();
            }
        }

        /// <summary>Burned-in MACs of real adapters. Virtual, VPN and randomised (locally administered) MACs are skipped.</summary>
        internal static List<string> PhysicalMacs()
        {
            string[] skip = { "virtual", "vmware", "hyper-v", "vbox", "virtualbox", "vpn", "tap-", "tap ", "tun", "loopback", "bluetooth", "miniport",
                              "npcap", "docker", "wsl", "pseudo", "teredo", "isatap", "wi-fi direct", "tailscale", "zerotier", "wireguard", "hamachi",
                              "anyconnect", "fortinet", "vethernet", "kernel debug" };
            List<string> macs = new List<string>();
            foreach (NetworkInterface nic in NetworkInterface.GetAllNetworkInterfaces())
            {
                NetworkInterfaceType t = nic.NetworkInterfaceType;
                if (t != NetworkInterfaceType.Ethernet && t != NetworkInterfaceType.Wireless80211 && t != NetworkInterfaceType.GigabitEthernet &&
                    t != NetworkInterfaceType.FastEthernetT && t != NetworkInterfaceType.FastEthernetFx) continue;
                string label = ((nic.Description ?? "") + " " + (nic.Name ?? "")).ToLowerInvariant();
                if (skip.Any(k => label.Contains(k))) continue;
                byte[] a = nic.GetPhysicalAddress().GetAddressBytes();
                if (a.Length != 6 || a.All(b => b == 0)) continue;
                if ((a[0] & 0x02) != 0 || (a[0] & 0x01) != 0) continue; // locally administered (random/spoofed) or multicast
                macs.Add(BitConverter.ToString(a).Replace("-", "").ToLowerInvariant());
            }
            return macs.Distinct().OrderBy(m => m, StringComparer.Ordinal).Take(8).ToList();
        }

        private static void ReadSmbios(out string uuid, out string board, out string cpu)
        {
            const uint RSMB = 0x52534D42;
            uint size = Native.GetSystemFirmwareTable(RSMB, 0, null, 0);
            if (size == 0 || size > 1024 * 1024) { uuid = board = cpu = null; return; }
            byte[] buffer = new byte[size];
            if (Native.GetSystemFirmwareTable(RSMB, 0, buffer, size) != size) { uuid = board = cpu = null; return; }
            ParseSmbios(buffer, out uuid, out board, out cpu);
        }

        /// <summary>Parses a RawSMBIOSData blob: type 1 = system UUID, type 2 = baseboard serial, type 4 = processor id.</summary>
        internal static void ParseSmbios(byte[] raw, out string uuid, out string board, out string cpu)
        {
            uuid = board = cpu = null;
            if (raw == null || raw.Length < 8) return;
            int end = Math.Min(raw.Length, 8 + BitConverter.ToInt32(raw, 4));
            int pos = 8;
            while (pos + 4 <= end)
            {
                byte type = raw[pos];
                int len = raw[pos + 1];
                if (len < 4 || pos + len > end) break;
                List<string> strings = new List<string>();
                int p = pos + len;
                while (p + 1 < end && !(raw[p] == 0 && raw[p + 1] == 0))
                {
                    int start = p;
                    while (p < end && raw[p] != 0) p++;
                    strings.Add(Encoding.ASCII.GetString(raw, start, p - start));
                    if (p < end && raw[p] == 0 && p + 1 < end && raw[p + 1] == 0) break;
                    p++;
                }
                int next = p + 2;

                if (type == 1 && len >= 0x18 && uuid == null)
                {
                    byte[] u = new byte[16];
                    Array.Copy(raw, pos + 8, u, 0, 16);
                    string hex = BitConverter.ToString(u).Replace("-", "").ToLowerInvariant();
                    if (!u.All(b => b == 0) && !u.All(b => b == 0xFF) && hex != "03000200040005000006000700080009") uuid = hex;
                }
                else if (type == 2 && len >= 0x08 && board == null)
                {
                    int idx = raw[pos + 7];
                    if (idx > 0 && idx <= strings.Count) board = CleanSerial(strings[idx - 1]);
                }
                else if (type == 4 && len >= 0x10 && cpu == null)
                {
                    byte[] id = new byte[8];
                    Array.Copy(raw, pos + 8, id, 0, 8);
                    if (!id.All(b => b == 0)) cpu = BitConverter.ToString(id).Replace("-", "").ToLowerInvariant();
                }
                else if (type == 127) break;
                pos = next;
            }
        }

        private static string CleanSerial(string s)
        {
            if (s == null) return null;
            string v = s.Trim();
            string l = v.ToLowerInvariant();
            if (v.Length < 3 || l.Contains("o.e.m") || l.Contains("default") || l.Contains("filled") || l == "none" || l.Contains("not applicable") ||
                l.Contains("serial number") || l == "0123456789" || v.All(ch => ch == v[0])) return null;
            return v.ToUpperInvariant();
        }

        private static Dictionary<string, HashSet<string>> Parse(string raw)
        {
            Dictionary<string, HashSet<string>> map = new Dictionary<string, HashSet<string>>();
            if (string.IsNullOrEmpty(raw)) return map;
            foreach (string entry in raw.ToLowerInvariant().Split(',').Take(16))
            {
                string e = entry.Trim();
                int colon = e.IndexOf(':');
                if (colon <= 0) continue;
                string type = e.Substring(0, colon);
                string hash = e.Substring(colon + 1);
                if (Array.IndexOf(Types, type) < 0 || hash.Length != 16 || !hash.All(ch => (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f'))) continue;
                HashSet<string> set;
                if (!map.TryGetValue(type, out set))
                {
                    set = new HashSet<string>();
                    map[type] = set;
                }
                else if (type != "mac") continue;
                if (type == "mac" && set.Count >= 8) continue;
                set.Add(hash);
            }
            return map;
        }

        /// <summary>Same PC? With an SMBIOS UUID on both sides it must match and the score reach 6; otherwise a
        /// physical MAC must match and the score reach 4. Weights: uuid 3, mac/board/mg 2, cpu/vol 1.</summary>
        public static bool Same(string a, string b)
        {
            Dictionary<string, HashSet<string>> x = Parse(a), y = Parse(b);
            if (x.Count == 0 || y.Count == 0) return false;
            int score = 0;
            HashSet<string> matched = new HashSet<string>();
            foreach (string type in Types)
            {
                HashSet<string> xs, ys;
                if (!x.TryGetValue(type, out xs) || !y.TryGetValue(type, out ys)) continue;
                if (xs.Overlaps(ys))
                {
                    score += Weight(type);
                    matched.Add(type);
                }
            }
            if (x.ContainsKey("uuid") && y.ContainsKey("uuid")) return matched.Contains("uuid") && score >= 6;
            return matched.Contains("mac") && score >= 4;
        }
    }

    internal static class Native
    {
        [DllImport("kernel32.dll", SetLastError = true)]
        internal static extern uint GetSystemFirmwareTable(uint firmwareTableProviderSignature, uint firmwareTableId, byte[] firmwareTableBuffer, uint bufferSize);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        internal static extern bool GetVolumeInformation(string rootPathName, StringBuilder volumeNameBuffer, int volumeNameSize,
            out uint volumeSerialNumber, out uint maximumComponentLength, out uint fileSystemFlags, StringBuilder fileSystemNameBuffer, int fileSystemNameSize);
    }

    /// <summary>Windows DPAPI (current user) via P/Invoke - no extra references needed on .NET Framework or .NET 8.</summary>
    internal static class Dpapi
    {
        [StructLayout(LayoutKind.Sequential)]
        private struct DataBlob
        {
            public int cbData;
            public IntPtr pbData;
        }

        [DllImport("crypt32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        private static extern bool CryptProtectData(ref DataBlob dataIn, string description, ref DataBlob entropy, IntPtr reserved, IntPtr prompt, int flags, ref DataBlob dataOut);

        [DllImport("crypt32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        private static extern bool CryptUnprotectData(ref DataBlob dataIn, IntPtr description, ref DataBlob entropy, IntPtr reserved, IntPtr prompt, int flags, ref DataBlob dataOut);

        [DllImport("kernel32.dll")]
        private static extern IntPtr LocalFree(IntPtr mem);

        private const int UiForbidden = 0x1;

        public static byte[] Protect(byte[] data, byte[] entropy)
        {
            return Run(data, entropy, true);
        }

        public static byte[] Unprotect(byte[] data, byte[] entropy)
        {
            return Run(data, entropy, false);
        }

        private static byte[] Run(byte[] data, byte[] entropy, bool protect)
        {
            DataBlob input = ToBlob(data);
            DataBlob ent = ToBlob(entropy);
            DataBlob output = new DataBlob();
            try
            {
                bool ok = protect
                    ? CryptProtectData(ref input, "VEYLIX", ref ent, IntPtr.Zero, IntPtr.Zero, UiForbidden, ref output)
                    : CryptUnprotectData(ref input, IntPtr.Zero, ref ent, IntPtr.Zero, IntPtr.Zero, UiForbidden, ref output);
                if (!ok) throw new CryptographicException(Marshal.GetLastWin32Error());
                byte[] result = new byte[output.cbData];
                Marshal.Copy(output.pbData, result, 0, output.cbData);
                return result;
            }
            finally
            {
                if (input.pbData != IntPtr.Zero) Marshal.FreeHGlobal(input.pbData);
                if (ent.pbData != IntPtr.Zero) Marshal.FreeHGlobal(ent.pbData);
                if (output.pbData != IntPtr.Zero) LocalFree(output.pbData);
            }
        }

        private static DataBlob ToBlob(byte[] data)
        {
            DataBlob blob = new DataBlob { cbData = data.Length, pbData = Marshal.AllocHGlobal(Math.Max(1, data.Length)) };
            Marshal.Copy(data, 0, blob.pbData, data.Length);
            return blob;
        }
    }
}
`;

export function renderCSharpKit(values: { serverUrl: string; productSlug: string; productName: string; publicKeyXml: string; supportEmail: string }) {
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/[\r\n]/g, " ");
  return CSHARP_TEMPLATE.replaceAll("{{SERVER_URL}}", esc(values.serverUrl.replace(/\/$/, "")))
    .replaceAll("{{PRODUCT_SLUG}}", esc(values.productSlug))
    .replaceAll("{{PRODUCT_NAME}}", esc(values.productName))
    .replaceAll("{{PUBLIC_KEY_XML}}", esc(values.publicKeyXml))
    .replaceAll("{{SUPPORT_EMAIL}}", esc(values.supportEmail))
    .replaceAll("{{GENERATED_AT}}", new Date().toISOString().slice(0, 10));
}
