/**
 * C# licensing module for VEYLIX Revit add-ins. The admin panel fills in the placeholders per product
 * (server URL, product slug, RSA public key) and serves it as VeylixLicense.cs.
 *
 * Written for C# 7.3 so it compiles unchanged for .NET Framework 4.8 (Revit 2021–2024) and .NET 8 (Revit 2025+).
 * No NuGet packages: HTTP via HttpWebRequest, storage encryption via Windows DPAPI (P/Invoke).
 */
export const CSHARP_TEMPLATE = String.raw`// =====================================================================================
//  VeylixLicense.cs  -  licensing for "{{PRODUCT_NAME}}"  (product id: {{PRODUCT_SLUG}})
//  Generated by the VEYLIX admin panel on {{GENERATED_AT}}. Do not share this file publicly.
//
//  SETUP (once):
//   1. Add this file to your Revit add-in project.
//   2. WinForms is used for the key dialog:
//        .NET Framework 4.8 (Revit 2021-2024): reference System.Windows.Forms and System.Drawing
//        .NET 8 (Revit 2025+): add <UseWindowsForms>true</UseWindowsForms> to your .csproj
//   3. First line of EVERY IExternalCommand.Execute:
//        if (!Veylix.Licensing.VeylixLicense.Require()) return Result.Cancelled;
//   4. Optional ribbon button that shows time remaining / lets the user change key:
//        Veylix.Licensing.VeylixLicense.ShowStatus();
//   5. Rebuild, obfuscate the DLL (recommended), then upload the build folder in the admin panel.
//
//  HOW IT WORKS
//   - The user enters a product key. The server binds it to this PC and returns a license
//     signed with the VEYLIX RSA private key. This file only contains the PUBLIC key, so a
//     license cannot be forged or edited.
//   - The license is valid for the check interval set in the admin panel (default 30 days).
//     When it runs out, the plugin asks for the key again and shows the time remaining.
//   - The license file is encrypted with Windows DPAPI and tied to this PC's hardware ID.
//   - Moving the Windows clock back is detected. Revoked keys and device resets take effect
//     at the next online check (at most every 6 hours while Revit is running).
// =====================================================================================

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Win32;

namespace Veylix.Licensing
{
    public static class VeylixLicense
    {
        public const string ServerUrl = "{{SERVER_URL}}";
        public const string SupportEmail = "{{SUPPORT_EMAIL}}";
        public const string ProductSlug = "{{PRODUCT_SLUG}}";
        public const string ProductName = "{{PRODUCT_NAME}}";
        private const string PublicKeyXml = "{{PUBLIC_KEY_XML}}";

        private static readonly object Sync = new object();
        private static LicenseState _state;
        private static bool _loaded;
        private static int _refreshing;
        private static bool _warnedThisSession;

        /// <summary>True when a valid, unexpired license exists on this PC.</summary>
        public static bool IsLicensed
        {
            get { LicenseState s = Load(); return s != null && s.IsCurrentlyValid(); }
        }

        /// <summary>Time until the plugin asks for the product key again.</summary>
        public static TimeSpan RemainingTime
        {
            get
            {
                LicenseState s = Load();
                if (s == null) return TimeSpan.Zero;
                TimeSpan left = s.ValidUntilUtc - DateTime.UtcNow;
                return left < TimeSpan.Zero ? TimeSpan.Zero : left;
            }
        }

        /// <summary>
        /// Call at the start of every command. Returns true when the user may continue.
        /// Shows the product key dialog when there is no valid license.
        /// </summary>
        public static bool Require()
        {
            try
            {
                LicenseState s = Load();
                if (s != null && s.IsCurrentlyValid())
                {
                    s.LastSeenUtc = DateTime.UtcNow;
                    Save(s);
                    RefreshInBackground(s);
                    TimeSpan left = s.ValidUntilUtc - DateTime.UtcNow;
                    if (left.TotalDays < 3 && !_warnedThisSession)
                    {
                        _warnedThisSession = true;
                        MessageBox.Show(Owner(),
                            ProductName + ": your license check is due in " + FormatSpan(left) + ".\n" +
                            "You will be asked for your product key again then.",
                            "VEYLIX license", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                    return true;
                }

                string reason;
                if (s == null) reason = "Enter your product key to activate " + ProductName + " on this PC.";
                else if (s.ClockTampered) reason = "Your system clock was changed. Enter your product key to continue.";
                else if (s.IsTrial) reason = "Your free trial has ended. Enter a product key to keep using " + ProductName + ".";
                else reason = "It's time to confirm your license. Enter your product key to continue.";

                using (LicenseDialog dialog = new LicenseDialog(reason, s != null ? s.Key : ""))
                {
                    dialog.ShowDialog(Owner());
                    return dialog.KeyAccepted;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(Owner(), "License check failed: " + ex.Message, "VEYLIX license", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
        }

        /// <summary>Shows the license status (time remaining) and lets the user enter another key.</summary>
        public static void ShowStatus()
        {
            LicenseState s = Load();
            string text = s != null && s.IsCurrentlyValid()
                ? "Licensed. Key " + s.Key + "\nNext key check in " + FormatSpan(s.ValidUntilUtc - DateTime.UtcNow) +
                  (s.ExpiresAtUtc.HasValue ? "\nLicense ends " + s.ExpiresAtUtc.Value.ToLocalTime().ToString("d MMM yyyy", CultureInfo.InvariantCulture) : "") +
                  (s.IsTrial ? "\n(Free trial)" : "")
                : "Not activated on this PC.";
            using (LicenseDialog dialog = new LicenseDialog(text, s != null ? s.Key : ""))
            {
                dialog.ShowDialog(Owner());
            }
        }

        // ------------------------------------------------------------------ activation

        internal static bool Activate(string key, out string message)
        {
            string nonce = RandomToken(24);
            Dictionary<string, string> fields = new Dictionary<string, string>
            {
                { "key", key.Trim() },
                { "deviceId", DeviceId() },
                { "deviceName", Environment.MachineName },
                { "product", ProductSlug },
                { "nonce", nonce },
            };
            string[] lines;
            try
            {
                lines = Post("/api/license/activate", fields, 15000);
            }
            catch (Exception ex)
            {
                message = "Could not reach the license server. Check your internet connection.\n(" + ex.Message + ")";
                return false;
            }

            if (lines.Length >= 3 && lines[0] == "OK")
            {
                LicenseState s = LicenseState.FromSigned(lines[1], lines[2]);
                if (s == null || s.Nonce != nonce || s.DeviceId != DeviceId() || !s.MatchesProduct())
                {
                    message = "The server response could not be verified.";
                    return false;
                }
                s.LastSeenUtc = DateTime.UtcNow;
                s.LastOnlineUtc = DateTime.UtcNow;
                Save(s);
                message = "Activated. The next key check is in " + FormatSpan(s.ValidUntilUtc - DateTime.UtcNow) + ".";
                return true;
            }
            message = lines.Length >= 3 ? lines[2] : "Activation failed.";
            return false;
        }

        private static void RefreshInBackground(LicenseState s)
        {
            if ((DateTime.UtcNow - s.LastOnlineUtc).TotalHours < 6) return;
            if (Interlocked.Exchange(ref _refreshing, 1) == 1) return;
            string key = s.Key;
            Task.Run(() =>
            {
                try
                {
                    string nonce = RandomToken(24);
                    string[] lines = Post("/api/license/status", new Dictionary<string, string>
                    {
                        { "key", key },
                        { "deviceId", DeviceId() },
                        { "product", ProductSlug },
                        { "nonce", nonce },
                    }, 8000);

                    if (lines.Length >= 3 && lines[0] == "OK")
                    {
                        LicenseState fresh = LicenseState.FromSigned(lines[1], lines[2]);
                        if (fresh != null && fresh.Nonce == nonce && fresh.DeviceId == DeviceId() && fresh.MatchesProduct())
                        {
                            fresh.LastSeenUtc = DateTime.UtcNow;
                            fresh.LastOnlineUtc = DateTime.UtcNow;
                            Save(fresh); // adopts admin changes (shorter interval, forced re-check)
                        }
                    }
                    else if (lines.Length >= 2 && lines[0] == "ERROR")
                    {
                        string code = lines[1];
                        if (code == "revoked" || code == "device_mismatch" || code == "expired" || code == "invalid_key" || code == "not_activated" || code == "wrong_product")
                            Clear(); // key revoked or moved to another PC: ask again next time
                    }
                }
                catch
                {
                    // offline: keep working until the signed license runs out
                }
                finally
                {
                    Interlocked.Exchange(ref _refreshing, 0);
                }
            });
        }

        // ------------------------------------------------------------------ storage

        private static string StatePath()
        {
            string dir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "VEYLIX");
            Directory.CreateDirectory(dir);
            return Path.Combine(dir, ProductSlug + ".lic");
        }

        private static LicenseState Load()
        {
            lock (Sync)
            {
                if (_loaded) return _state;
                _loaded = true;
                try
                {
                    string path = StatePath();
                    if (!File.Exists(path)) return _state = null;
                    string text = Encoding.UTF8.GetString(Dpapi.Unprotect(File.ReadAllBytes(path), Entropy()));
                    string[] parts = text.Split('\n');
                    if (parts.Length < 4) return _state = null;
                    LicenseState s = LicenseState.FromSigned(parts[0], parts[1]);
                    if (s == null || s.DeviceId != DeviceId() || !s.MatchesProduct()) return _state = null;
                    s.LastSeenUtc = FromUnix(long.Parse(parts[2], CultureInfo.InvariantCulture));
                    s.LastOnlineUtc = FromUnix(long.Parse(parts[3], CultureInfo.InvariantCulture));
                    return _state = s;
                }
                catch
                {
                    return _state = null;
                }
            }
        }

        private static void Save(LicenseState s)
        {
            lock (Sync)
            {
                string text = s.Payload + "\n" + s.Signature + "\n" + ToUnix(s.LastSeenUtc).ToString(CultureInfo.InvariantCulture) + "\n" + ToUnix(s.LastOnlineUtc).ToString(CultureInfo.InvariantCulture);
                File.WriteAllBytes(StatePath(), Dpapi.Protect(Encoding.UTF8.GetBytes(text), Entropy()));
                _state = s;
                _loaded = true;
            }
        }

        private static void Clear()
        {
            lock (Sync)
            {
                try { File.Delete(StatePath()); } catch { }
                _state = null;
                _loaded = true;
            }
        }

        private static byte[] Entropy()
        {
            return Encoding.UTF8.GetBytes("VEYLIX|" + ProductSlug);
        }

        // ------------------------------------------------------------------ crypto & device

        internal static bool VerifySignature(string payload, string signatureBase64)
        {
            try
            {
                using (RSA rsa = new RSACng())
                {
                    rsa.FromXmlString(PublicKeyXml);
                    return rsa.VerifyData(Encoding.UTF8.GetBytes(payload), Convert.FromBase64String(signatureBase64), HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
                }
            }
            catch
            {
                return false;
            }
        }

        private static string _deviceId;

        /// <summary>Stable per-PC ID: hash of the Windows machine GUID, system volume serial and computer name.</summary>
        public static string DeviceId()
        {
            if (_deviceId != null) return _deviceId;
            string machineGuid = "";
            try
            {
                using (RegistryKey hklm = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64))
                using (RegistryKey k = hklm.OpenSubKey(@"SOFTWARE\Microsoft\Cryptography"))
                {
                    if (k != null) machineGuid = (k.GetValue("MachineGuid") as string) ?? "";
                }
            }
            catch { }

            uint serial = 0;
            try
            {
                uint maxLen, flags;
                string root = Path.GetPathRoot(Environment.SystemDirectory);
                Native.GetVolumeInformation(root, null, 0, out serial, out maxLen, out flags, null, 0);
            }
            catch { }

            string raw = machineGuid + "|" + serial.ToString("X8", CultureInfo.InvariantCulture) + "|" + Environment.MachineName.ToUpperInvariant();
            using (SHA256 sha = SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(Encoding.UTF8.GetBytes(raw));
                StringBuilder sb = new StringBuilder("W1-");
                for (int i = 0; i < 20; i++) sb.Append(hash[i].ToString("x2", CultureInfo.InvariantCulture));
                _deviceId = sb.ToString();
            }
            return _deviceId;
        }

        private static string RandomToken(int length)
        {
            const string alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
            byte[] bytes = new byte[length];
            using (RandomNumberGenerator rng = RandomNumberGenerator.Create()) rng.GetBytes(bytes);
            StringBuilder sb = new StringBuilder(length);
            foreach (byte b in bytes) sb.Append(alphabet[b % alphabet.Length]);
            return sb.ToString();
        }

        // ------------------------------------------------------------------ HTTP

        private static string[] Post(string path, IDictionary<string, string> fields, int timeoutMs)
        {
#pragma warning disable SYSLIB0014 // WebRequest/ServicePointManager: kept for .NET Framework 4.8 compatibility
            ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
            string body = string.Join("&", fields.Select(f => Uri.EscapeDataString(f.Key) + "=" + Uri.EscapeDataString(f.Value)).ToArray());
            HttpWebRequest req = (HttpWebRequest)WebRequest.Create(ServerUrl.TrimEnd('/') + path + "?format=text");
#pragma warning restore SYSLIB0014
            req.Method = "POST";
            req.ContentType = "application/x-www-form-urlencoded";
            req.UserAgent = "VeylixLicense/1 (" + ProductSlug + ")";
            req.Timeout = timeoutMs;
            req.ReadWriteTimeout = timeoutMs;
            byte[] bytes = Encoding.UTF8.GetBytes(body);
            req.ContentLength = bytes.Length;
            using (Stream s = req.GetRequestStream()) s.Write(bytes, 0, bytes.Length);
            try
            {
                using (HttpWebResponse resp = (HttpWebResponse)req.GetResponse()) return ReadLines(resp);
            }
            catch (WebException ex)
            {
                HttpWebResponse resp = ex.Response as HttpWebResponse;
                if (resp == null) throw;
                using (resp) return ReadLines(resp);
            }
        }

        private static string[] ReadLines(HttpWebResponse resp)
        {
            using (StreamReader reader = new StreamReader(resp.GetResponseStream(), Encoding.UTF8))
            {
                return reader.ReadToEnd().Replace("\r", "").Split('\n');
            }
        }

        // ------------------------------------------------------------------ helpers

        internal static DateTime FromUnix(long seconds)
        {
            return new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddSeconds(seconds);
        }

        internal static long ToUnix(DateTime utc)
        {
            return (long)(utc - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalSeconds;
        }

        internal static string FormatSpan(TimeSpan t)
        {
            if (t <= TimeSpan.Zero) return "0 minutes";
            if (t.TotalDays >= 1) return (int)t.TotalDays + " day" + ((int)t.TotalDays == 1 ? "" : "s") + ", " + t.Hours + " hour" + (t.Hours == 1 ? "" : "s");
            if (t.TotalHours >= 1) return (int)t.TotalHours + " hour" + ((int)t.TotalHours == 1 ? "" : "s");
            return Math.Max(1, (int)t.TotalMinutes) + " minutes";
        }

        internal static IWin32Window Owner()
        {
            return new WindowHandle(Process.GetCurrentProcess().MainWindowHandle);
        }

        private sealed class WindowHandle : IWin32Window
        {
            public WindowHandle(IntPtr handle) { Handle = handle; }
            public IntPtr Handle { get; private set; }
        }
    }

    internal sealed class LicenseState
    {
        public string Payload;
        public string Signature;
        public string Key;
        public string DeviceId;
        public string Scope;
        public DateTime ValidUntilUtc;
        public DateTime IssuedAtUtc;
        public DateTime? ExpiresAtUtc;
        public int CheckDays;
        public bool IsTrial;
        public string Nonce;
        public DateTime LastSeenUtc;
        public DateTime LastOnlineUtc;

        /// <summary>True when the Windows clock is earlier than a time this license has already seen.</summary>
        public bool ClockTampered
        {
            get
            {
                DateTime now = DateTime.UtcNow;
                return now < LastSeenUtc.AddMinutes(-10) || now < IssuedAtUtc.AddHours(-24);
            }
        }

        public bool IsCurrentlyValid()
        {
            return !ClockTampered && DateTime.UtcNow < ValidUntilUtc && (!ExpiresAtUtc.HasValue || DateTime.UtcNow < ExpiresAtUtc.Value);
        }

        public bool MatchesProduct()
        {
            return Scope == "*" || Scope == VeylixLicense.ProductSlug;
        }

        /// <summary>Parses VLX1|key|device|scope|validUntil|issuedAt|expiresAt|days|trial|nonce after checking the RSA signature.</summary>
        public static LicenseState FromSigned(string payload, string signature)
        {
            if (string.IsNullOrEmpty(payload) || string.IsNullOrEmpty(signature)) return null;
            if (!VeylixLicense.VerifySignature(payload, signature)) return null;
            string[] p = payload.Split('|');
            if (p.Length < 10 || p[0] != "VLX1") return null;
            long expires = long.Parse(p[6], CultureInfo.InvariantCulture);
            return new LicenseState
            {
                Payload = payload,
                Signature = signature,
                Key = p[1],
                DeviceId = p[2],
                Scope = p[3],
                ValidUntilUtc = VeylixLicense.FromUnix(long.Parse(p[4], CultureInfo.InvariantCulture)),
                IssuedAtUtc = VeylixLicense.FromUnix(long.Parse(p[5], CultureInfo.InvariantCulture)),
                ExpiresAtUtc = expires > 0 ? (DateTime?)VeylixLicense.FromUnix(expires) : null,
                CheckDays = int.Parse(p[7], CultureInfo.InvariantCulture),
                IsTrial = p[8] == "1",
                Nonce = p[9],
                LastSeenUtc = DateTime.UtcNow,
                LastOnlineUtc = DateTime.UtcNow,
            };
        }
    }

    internal sealed class LicenseDialog : Form
    {
        private readonly TextBox _key;
        private readonly Label _message;
        private readonly Button _activate;
        public bool KeyAccepted { get; private set; }

        public LicenseDialog(string message, string currentKey)
        {
            Text = VeylixLicense.ProductName + " - License";
            FormBorderStyle = FormBorderStyle.FixedDialog;
            StartPosition = FormStartPosition.CenterParent;
            MaximizeBox = false;
            MinimizeBox = false;
            ShowInTaskbar = false;
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(460, 250);
            Font = new Font("Segoe UI", 9.5f);
            BackColor = Color.FromArgb(18, 20, 26);
            ForeColor = Color.FromArgb(245, 247, 250);

            Label title = new Label { Text = "VEYLIX  " + VeylixLicense.ProductName, Font = new Font("Segoe UI Semibold", 12f), AutoSize = true, Location = new Point(20, 18), ForeColor = Color.FromArgb(0, 229, 255) };
            _message = new Label { Text = message, Location = new Point(20, 52), Size = new Size(420, 58), ForeColor = Color.FromArgb(201, 206, 216) };
            Label keyLabel = new Label { Text = "Product key", AutoSize = true, Location = new Point(20, 116), ForeColor = Color.FromArgb(139, 146, 161) };
            _key = new TextBox { Text = currentKey ?? "", Location = new Point(20, 136), Size = new Size(420, 28), Font = new Font("Consolas", 11f), CharacterCasing = CharacterCasing.Upper };
            _activate = new Button { Text = "Activate", Location = new Point(330, 196), Size = new Size(110, 32), BackColor = Color.FromArgb(0, 229, 255), ForeColor = Color.FromArgb(0, 22, 26), FlatStyle = FlatStyle.Flat };
            _activate.FlatAppearance.BorderSize = 0;
            Button buy = new Button { Text = "Buy / free trial", Location = new Point(190, 196), Size = new Size(130, 32), FlatStyle = FlatStyle.Flat, ForeColor = Color.FromArgb(245, 247, 250) };
            Button close = new Button { Text = "Close", Location = new Point(20, 196), Size = new Size(90, 32), FlatStyle = FlatStyle.Flat, ForeColor = Color.FromArgb(139, 146, 161), DialogResult = DialogResult.Cancel };

            LinkLabel help = new LinkLabel { Text = "Need help? " + VeylixLicense.SupportEmail, AutoSize = true, Location = new Point(20, 170), LinkColor = Color.FromArgb(0, 229, 255), ActiveLinkColor = Color.FromArgb(94, 240, 255), ForeColor = Color.FromArgb(139, 146, 161) };
            help.LinkArea = new LinkArea("Need help? ".Length, VeylixLicense.SupportEmail.Length);
            help.LinkClicked += delegate
            {
                try { Process.Start(new ProcessStartInfo("mailto:" + VeylixLicense.SupportEmail + "?subject=" + Uri.EscapeDataString(VeylixLicense.ProductName + " license")) { UseShellExecute = true }); } catch { }
            };

            _activate.Click += OnActivate;
            buy.Click += delegate
            {
                try { Process.Start(new ProcessStartInfo(VeylixLicense.ServerUrl.TrimEnd('/') + "/en/products/" + VeylixLicense.ProductSlug) { UseShellExecute = true }); } catch { }
            };

            Controls.AddRange(new Control[] { title, _message, keyLabel, _key, help, _activate, buy, close });
            AcceptButton = _activate;
            CancelButton = close;
        }

        private void OnActivate(object sender, EventArgs e)
        {
            string key = _key.Text.Trim();
            if (key.Length < 10)
            {
                _message.Text = "Enter the product key you received (VLX-XXXX-XXXX-XXXX-XXXX).";
                return;
            }
            _activate.Enabled = false;
            Cursor = Cursors.WaitCursor;
            string result;
            bool ok = VeylixLicense.Activate(key, out result);
            Cursor = Cursors.Default;
            _activate.Enabled = true;
            _message.Text = result;
            _message.ForeColor = ok ? Color.FromArgb(34, 211, 170) : Color.FromArgb(255, 92, 122);
            if (ok)
            {
                KeyAccepted = true;
                DialogResult = DialogResult.OK;
                MessageBox.Show(this, result, "VEYLIX license", MessageBoxButtons.OK, MessageBoxIcon.Information);
                Close();
            }
        }
    }

    internal static class Native
    {
        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        internal static extern bool GetVolumeInformation(string rootPathName, StringBuilder volumeNameBuffer, int volumeNameSize,
            out uint volumeSerialNumber, out uint maximumComponentLength, out uint fileSystemFlags, StringBuilder fileSystemNameBuffer, int fileSystemNameSize);
    }

    /// <summary>Windows DPAPI (current user) via P/Invoke - no extra references needed on .NET Framework or .NET 8.</summary>
    internal static class Dpapi
    {
        [StructLayout(LayoutKind.Sequential)]
        private struct DataBlob
        {
            public int cbData;
            public IntPtr pbData;
        }

        [DllImport("crypt32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        private static extern bool CryptProtectData(ref DataBlob dataIn, string description, ref DataBlob entropy, IntPtr reserved, IntPtr prompt, int flags, ref DataBlob dataOut);

        [DllImport("crypt32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        private static extern bool CryptUnprotectData(ref DataBlob dataIn, IntPtr description, ref DataBlob entropy, IntPtr reserved, IntPtr prompt, int flags, ref DataBlob dataOut);

        [DllImport("kernel32.dll")]
        private static extern IntPtr LocalFree(IntPtr mem);

        private const int UiForbidden = 0x1;

        public static byte[] Protect(byte[] data, byte[] entropy)
        {
            return Run(data, entropy, true);
        }

        public static byte[] Unprotect(byte[] data, byte[] entropy)
        {
            return Run(data, entropy, false);
        }

        private static byte[] Run(byte[] data, byte[] entropy, bool protect)
        {
            DataBlob input = ToBlob(data);
            DataBlob ent = ToBlob(entropy);
            DataBlob output = new DataBlob();
            try
            {
                bool ok = protect
                    ? CryptProtectData(ref input, "VEYLIX", ref ent, IntPtr.Zero, IntPtr.Zero, UiForbidden, ref output)
                    : CryptUnprotectData(ref input, IntPtr.Zero, ref ent, IntPtr.Zero, IntPtr.Zero, UiForbidden, ref output);
                if (!ok) throw new CryptographicException(Marshal.GetLastWin32Error());
                byte[] result = new byte[output.cbData];
                Marshal.Copy(output.pbData, result, 0, output.cbData);
                return result;
            }
            finally
            {
                if (input.pbData != IntPtr.Zero) Marshal.FreeHGlobal(input.pbData);
                if (ent.pbData != IntPtr.Zero) Marshal.FreeHGlobal(ent.pbData);
                if (output.pbData != IntPtr.Zero) LocalFree(output.pbData);
            }
        }

        private static DataBlob ToBlob(byte[] data)
        {
            DataBlob blob = new DataBlob { cbData = data.Length, pbData = Marshal.AllocHGlobal(Math.Max(1, data.Length)) };
            Marshal.Copy(data, 0, blob.pbData, data.Length);
            return blob;
        }
    }
}
`;

export function renderCSharpKit(values: { serverUrl: string; productSlug: string; productName: string; publicKeyXml: string; supportEmail: string }) {
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/[\r\n]/g, " ");
  return CSHARP_TEMPLATE.replaceAll("{{SERVER_URL}}", esc(values.serverUrl.replace(/\/$/, "")))
    .replaceAll("{{PRODUCT_SLUG}}", esc(values.productSlug))
    .replaceAll("{{PRODUCT_NAME}}", esc(values.productName))
    .replaceAll("{{PUBLIC_KEY_XML}}", esc(values.publicKeyXml))
    .replaceAll("{{SUPPORT_EMAIL}}", esc(values.supportEmail))
    .replaceAll("{{GENERATED_AT}}", new Date().toISOString().slice(0, 10));
}
